controller:
  deploy: true
  name: tink-controller
  image: quay.io/tinkerbell/tink-controller:v0.10.0
  imagePullPolicy: IfNotPresent
  replicas: 1
  args: []
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi
  roleName: tink-controller-manager-role
  roleBindingName: tink-controller-manager-rolebinding
  tinkLeaderElectionRoleName: tink-leader-election-role
  tinkLeaderElectionRoleBindingName: tink-leader-election-rolebinding
  nodeSelector: {}
  # singleNodeClusterConfig to add tolerations for deployments on control plane nodes. This is defaulted to false.
  singleNodeClusterConfig:
    controlPlaneTolerationsEnabled: false
    weight: 1

server:
  deploy: true
  name: tink-server
  image: quay.io/tinkerbell/tink:v0.10.0
  imagePullPolicy: IfNotPresent
  replicas: 1
  service:
    port: 42113
  deployment:
    port: 42113
    portName: tink-grpc
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi
  roleName: tink-server-role
  roleBindingName: tink-server-rolebinding
  nodeSelector: {}
  # singleNodeClusterConfig to add tolerations for deployments on control plane nodes. This is defaulted to false.
  singleNodeClusterConfig:
    controlPlaneTolerationsEnabled: false
    nodeAffinityWeight: 1
