version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "America/New_York"
    reviewers:
      - chrisdoherty4

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "America/New_York"
    reviewers:
      - chrisdoherty4

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "05:00"
      timezone: "America/New_York"
    reviewers:
      - chrisdoherty4
