coverage:
  status:
    project:
      default:
        informational: true

ignore:
  - pkg/proto/workflow_grpc.pb.go
  - pkg/proto/workflow.pb.go
  - "**/zz_generated.deepcopy.go"
  - smee/internal/syslog/facility_string.go
  - smee/internal/syslog/severity_string.go
