coverage:
  status:
    patch: off
    project:
      default:
        informational: true
        threshold: 1%

ignore:
  - "pkg/proto/*.go"
  - "**/zz_generated.deepcopy.go"
  - "smee/internal/syslog/facility_string.go"
  - "smee/internal/syslog/severity_string.go"
  - "cmd"
