{{- if .Values.hegel.deploy }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.hegel.roleName }}
  namespace: {{ .Release.Namespace | quote }}
rules:
  - apiGroups:
      - tinkerbell.org
    resources:
      - hardware
      - hardware/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - tinkerbell.org
    resources:
      - workflows
      - workflows/status
    verbs:
      - get
      - list
      - watch
{{- end }}
