stack:
  enabled: true
  name: tink-stack
  service:
    enabled: true
    type: LoadBalancer
    annotations: {}
  selector:
    app: tink-stack
  nodeSelector: {}
  deployment:
    strategy:
      type: RollingUpdate
  # stack needs to resolve DNS names in the cluster (in .svc.clusterDomain)
  clusterDomain: cluster.local
  # loadBalancerIP will override the global.publicIP value if set
  # loadBalancerIP: 192.168.2.112
  lbClass: kube-vip.io/kube-vip-class
  # Once the Kubernetes Gateway API is more stable, we will use that for all services instead of nginx.
  image: nginx:1.27.2

  hook:
    enabled: true
    name: hook-files
    port: 8080
    image: bash:5.2.37
    # downloadURL only works with the > 0.8.1 Hook release because
    # previous Hook versions didn't provide a checksum file.
    downloadURL: https://github.com/tinkerbell/hook/releases/download/v0.10.0
    arch: both # x86_64, aarch64, both
    extension: tar.gz # iso, tar.gz, both
    kernelVersion: both # 5.10, 6.6, both
    persistence:
      # If existingClaim is set, the local persistence volume (localPersistentVolume) objects will NOT be created.
      # Use this to point to an existing production grade storage class.
      existingClaim: ""
      # While local storage is the default, it is not recommended for production use.
      localPersistentVolume:
        storageClassName: local-storage
        # this path must already exist on the node
        path: /tmp
        name: hook-artifacts
        accessModes:
          - ReadWriteMany
        size: 2Gi
        extraLabels: {}

  kubevip:
    enabled: true
    name: kube-vip
    image: ghcr.io/kube-vip/kube-vip:v0.8.7
    imagePullPolicy: IfNotPresent
    roleName: kube-vip-role
    roleBindingName: kube-vip-rolebinding
    # Customize the interface KubeVIP advertises on. When unset, KubeVIP will autodetect the interface.
    # interface: enp0s8

    # Additional environment variables to pass to the kubevip container. Each entry is expected to have a
    # name and value key. Some keys are already defined - refer to the deployment.yaml template for
    # details.
    #
    # Example
    #   - name: MY_ENV_VAR
    #     value: my-value
    additionalEnv: []
  # Relay allows us to listen and respond to layer broadcast DHCP requests
  relay:
    name: dhcp-relay
    enabled: true
    # This image (ghcr.io/jacobweinstock/dhcrelay) is used because the other public dhcprelay images out there (`modem7/dhcprelay`)
    # don't respect signals properly when run as PID 1.
    image: ghcr.io/jacobweinstock/dhcprelay # dhcprelay is a multiarch-enabled version of dhcrelay
    # if `interfaceMode: ipvlan`, then ghcr.io/jacobweinstock/relay-init:v0.1.0 (has nmap and nmap-scripts) is required. Otherwise, alpine can be used. 
    initImage: ghcr.io/jacobweinstock/relay-init:v0.1.0
    maxHopCount: 10
    # The presentGiaddrAction pertains to the course of action when the giaddr field appears in the DHCP packet.
    # In situations where another DHCP relay agent is already in operation within the environment,
    # maintaining option (82) in its received state from the dhcrelay might be essential.
    # This behavior can be regulated by configuring the presentGiaddrAction as "forward."
    # Additional information is available at: https://linux.die.net/man/8/dhcrelay
    presentGiaddrAction: forward
    # sourceInterface is the Host/Node interface to use for listening for DHCP broadcast packets.
    # When unset, the interface from the default route will be used.
    # sourceInterface: eno1
    # enable/disable listening for broadcast traffic. Useful when the environment employs DHCP relay agent(s).
    # default is true.
    listenBroadcastTraffic: true
    # interfaceMode determines how we create the interface needed to listen for DHCP broadcast traffic.
    # by default macvlan is used. ipvlan is the only other option.
    interfaceMode: macvlan
  # singleNodeClusterConfig to add tolerations for deployments on control plane nodes. This is defaulted to false.
  singleNodeClusterConfig:
    controlPlaneTolerationsEnabled: false
    nodeAffinityWeight: 1

# -- Overrides
# The values defined here override those in the individual charts. Some of them require tweaking
# before deployment as they are environment dependent; others are surfaced for convenience.
#
# See individual chart documentation for additional detail.

smee:
  name: tinkerbell
  hostNetwork: false
  deploy: true
  tftp:
    port: 69
    name: tftp
  syslog:
    port: 514
    name: syslog
  http:
    port: 7171
    name: http-ipxe

hegel:
  name: tinkerbell
  deployment:
    port: 50061
    portName: http-tootles
  service:
    port: 50061

tink:
  server:
    name: tinkerbell
    deployment:
      port: 42113
      portName: grpc
    service:
      port: 42113

# -- Global values
global:
  # publicIP is used to set what both smee.publicIP and stack.loadBalancerIP do individually.
  publicIP: 192.168.2.114
  trustedProxies: []
  rbac:
    type: Role
  nodeSelector: {} 
