apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tinkerbell
  namespace: "tinkerbell"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tinkerbell
subjects:
- kind: ServiceAccount
  name: tinkerbell
  namespace: "tinkerbell"
