{{- if .Values.server.deploy }}
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ .Values.server.rbac.type }}
metadata:
  name: {{ .Values.server.rbac.name }}
  {{- if eq .Values.server.rbac.type "Role"  }}
  namespace: {{ .Release.Namespace | quote }}
  {{- end }}
rules:
  - apiGroups:
      - tinkerbell.org
    resources:
      - hardware
      - hardware/status
      - templates
      - templates/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - tinkerbell.org
    resources:
      - workflows
      - workflows/status
    verbs:
      - get
      - list
      - patch
      - update
      - watch
{{- end }}
