name: For each commit and PR
on:
  push:
  pull_request:

jobs:
  validation:
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 0
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.14.6'
    - name: goimports
      run: go get golang.org/x/tools/cmd/goimports && goimports -d . | (! grep .)
    - name: go vet
      run: go vet ./...
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.31
    - name: go test
      run: go test -coverprofile=coverage.txt ./...
    - name: upload codecov
      run: bash <(curl -s https://codecov.io/bash)
    - uses: cachix/install-nix-action@v10
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: ./ci-checks.sh
  docker-images:
    runs-on: ubuntu-latest
    needs: [validation]
    strategy:
      matrix:
        include:
          - repository: quay.io/tinkerbell/tink-cli
            file: ./cmd/tink-cli/Dockerfile
          - repository: quay.io/tinkerbell/tink
            file: ./cmd/tink-server/Dockerfile
          - repository: quay.io/tinkerbell/tink-worker
            file: ./cmd/tink-worker/Dockerfile
    steps:
    - name: Docker Image Tag for Sha
      id: docker-image-tag
      run: |
        echo ::set-output name=tags::${{ matrix.repository }}:latest,${{ matrix.repository }}:sha-${GITHUB_SHA::8}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Login to quay.io
      uses: docker/login-action@v1
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: ${{ matrix.repository }}
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ${{ matrix.file }}
        cache-from: type=registry,ref=${{ matrix.repository }}:latest
        push: ${{ startsWith(github.ref, 'refs/heads/master') }}
        tags: ${{ steps.docker-image-tag.outputs.tags }}
        platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
