---
coverage:
  precision: 0 # xx%
  round: down # round down
  range: 30..40 # red < yellow (this range) < green

  status:
    project:
      default:
        target: auto # automatically calculate coverage target - should increase
        threshold: 2% # allow for 2% reduction without failing
    patch:
      default:
        target: auto
    changes: false
