name: For each commit and PR
on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "v*"
  pull_request:

jobs:
  validation:
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 0
    steps:
      - name: Setup Dynamic Env
        run: |
          echo "MAKEFLAGS=-j$(nproc)" | tee $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Install nix
        uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable

      - name: Fetch Deps
        run: nix-shell --run 'go get -t ./... && go mod tidy'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Go
        uses: actions/setup-go@75726802f3f367f1a0ac12b135b50a9b28e6d89c
        with:
          go-version: "1.18"

      - name: Generate all files
        run: nix-shell --run 'make -j1 gen'

      - name: Run all the tests
        run: nix-shell --run 'make ci'

      - name: upload codecov
        run: bash <(curl -s https://codecov.io/bash)

      - name: compile binaries
        run: nix-shell --run 'make crosscompile'

      - name: Docker Image Tag for Sha
        id: docker-image-tag
        run: |
          echo ::set-output name=tags::quay.io/tinkerbell/boots:latest,quay.io/tinkerbell/boots:sha-${GITHUB_SHA::8}

      - name: Login to quay.io
        uses: docker/login-action@v1
        if: ${{ startsWith(github.ref, 'refs/heads/main') }}
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Build Docker Images
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          cache-from: type=registry,ref=quay.io/tinkerbell/boots:latest
          push: ${{ startsWith(github.ref, 'refs/heads/main') }}
          tags: ${{ steps.docker-image-tag.outputs.tags }}
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
