{{- if .Values.controller.deploy }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.controller.name }}
  name: {{ .Values.controller.name }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: {{ .Values.controller.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.controller.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.controller.name }}
    spec:
      {{- with .Values.controller.nodeSelector }}
      nodeSelector: 
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - image: {{ .Values.controller.image }}
          imagePullPolicy: {{ .Values.controller.imagePullPolicy }}
          {{- if .Values.controller.args }}
          args: 
          {{- range .Values.controller.args }}
            - {{ . }}
          {{- end }}
          {{- end }}
          name: {{ .Values.controller.name }}
          resources:
            limits:
              cpu: {{ .Values.controller.resources.limits.cpu }}
              memory: {{ .Values.controller.resources.limits.memory }}
            requests:
              cpu: {{ .Values.controller.resources.requests.cpu }}
              memory: {{ .Values.controller.resources.requests.memory }}
      serviceAccountName: {{ .Values.controller.name }}
      {{- if .Values.controller.singleNodeClusterConfig.controlPlaneTolerationsEnabled }}
      tolerations:
      {{- include "singleNodeClusterConfig" . | indent 6 }}
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          {{- include "preferWorkerNodes" (dict "nodeAffinityWeight" .Values.controller.singleNodeClusterConfig.nodeAffinityWeight) | indent 10 }}
      {{- end }}
{{- end }}
