{{- if .Values.controller.deploy }}
{{- $roleType := .Values.controller.rbac.type }}
{{- if .Values.global }}
{{- $roleType = coalesce .Values.global.rbac.type .Values.controller.rbac.type }}
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ $roleType }}
metadata:
  name: {{ .Values.controller.rbac.name }}
  {{- if eq $roleType "Role"  }}
  namespace: {{ .Release.Namespace | quote }}
  {{- end }}
rules:
- apiGroups:
  - bmc.tinkerbell.org
  resources:
  - jobs
  - jobs/status
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - tinkerbell.org
  resources:
  - hardware
  - hardware/status
  - templates
  - templates/status
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tinkerbell.org
  resources:
  - workflows
  - workflows/status
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
{{- end }}
