{{- if .Values.controller.deploy }}
{{- $roleType := .Values.controller.rbac.type }}
{{- if .Values.global }}
{{- $roleType = coalesce .Values.global.rbac.type .Values.controller.rbac.type }}
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ $roleType }}Binding
metadata:
  name: {{ .Values.controller.rbac.bindingName }}
  {{- if eq $roleType "Role"  }}
  namespace: {{ .Release.Namespace | quote }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ $roleType }}
  name: {{ .Values.controller.rbac.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.controller.name }}
    namespace: {{ .Release.Namespace | quote }}
{{- end }}
