{{- if .Values.controller.deploy }}
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ .Values.controller.rbac.type }}Binding
metadata:
  name: {{ .Values.controller.rbac.bindingName }}
  {{- if eq .Values.controller.rbac.type "Role"  }}
  namespace: {{ .Release.Namespace | quote }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ .Values.controller.rbac.type }}
  name: {{ .Values.controller.rbac.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.controller.name }}
    namespace: {{ .Release.Namespace | quote }}
{{- end }}
