---

workspace:
  base: /go
  path: src/github.com/tinkerbell/tink

pipeline:
  test:
    group: ci
    image: golang:1.13-alpine
    commands:
      - CGO_ENABLED=0 go test -v ./...

  build:
    group: ci
    image: golang:1.13-alpine
    commands:
      - CGO_ENABLED=0 go build

  publish_pr:
    group: publish
    image: plugins/docker
    registry: quay.io
    repo: quay.io/tinkerbell/tink-pr
    tags:
      - ${DRONE_PULL_REQUEST}
      - ${DRONE_PULL_REQUEST}-${DRONE_BUILD_NUMBER}-${DRONE_COMMIT_SHA}
    when:
      event: pull_request
    secrets:
      - source: public_docker_password
        target: docker_password
      - source: public_docker_username
        target: docker_username

  publish_master:
    group: publish
    image: plugins/docker
    registry: quay.io
    repo: quay.io/tinkerbell/tink
    tags:
      - latest
      - ${DRONE_BUILD_NUMBER}-${DRONE_COMMIT_SHA}
    when:
      branch: master
      event: push
    secrets: 
      - docker_password
      - docker_username
    
  publish_tag:
    group: publish
    image: plugins/docker
    registry: quay.io
    repo: quay.io/tinkerbell/tink
    tags: ${DRONE_TAG}
    when:
      event: tag
    secrets:
      - docker_password
      - docker_username
