---

workspace:
  base: /go
  path: src/github.com/tinkerbell/tink

pipeline:
  test:
    group: ci
    image: golang:1.13-alpine
    commands:
      - go test -v ./...

  build:
    group: ci
    image: golang:1.13-alpine
    commands:
      - CGO_ENABLED=0 go build

  publish:
    group: publish
    image: plugins/docker
    registry: quay.io
    repo: quay.io/tinkerbell/tink
    tags:
      - ${DRONE_BRANCH/\//-}
      - ${DRONE_BUILD_NUMBER}-${DRONE_COMMIT_SHA}
    when:
      event: [push]
    secrets: [docker_username, docker_password]

  publish_tag:
    group: publish
    image: plugins/docker
    registry: quay.io
    repo: quay.io/tinkerbell/tink
    tags: ${DRONE_TAG}
    when:
      event: [tag]
    secrets: [docker_username, docker_password]
