---

workspace:
  base: /go
  path: src/github.com/packethost/tinkerbell

pipeline:
  test:
    group: ci
    image: golang:1.10-alpine
    commands:
      - go test -v ./...

  build:
    group: ci
    image: golang:1.10-alpine
    commands:
      - CGO_ENABLED=0 go build


