pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - base=master
      - "#approved-reviews-by>=1"
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
      - "#commented-reviews-by=0"
      - label=ready-to-merge
      - label!=hold-off-merging
    actions:
      merge:
        commit_message: title+body
        strict: smart+fastpath
