version: "3.8"
services:
  tinkerbell:
    build:
      context: ./cmd/tink-server/
      dockerfile: Dockerfile
    environment:
      FACILITY: ${FACILITY:-onprem}
      PACKET_ENV: ${PACKET_ENV:-testing}
      PACKET_VERSION: ${PACKET_VERSION:-ignored}
      ROLLBAR_TOKEN: ${ROLLBAR_TOKEN:-ignored}
      ROLLBAR_DISABLE: ${ROLLBAR_DISABLE:-1}
      PGDATABASE: tinkerbell
      PGHOST: db
      PGPASSWORD: tinkerbell
      PGPORT: 5432
      PGSSLMODE: disable
      PGUSER: tinkerbell
      TINKERBELL_GRPC_AUTHORITY: :42113
      TINKERBELL_HTTP_AUTHORITY: :42114
    volumes:
      - certs:/certs/${FACILITY:-onprem}:rw
    ports:
      - 42113:42113/tcp
      - 42114:42114/tcp
    depends_on:
      db:
        condition: service_healthy
      tink-server-migration:
        condition: service_started
      tls-gen:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- 127.0.0.1:42114/healthz"] # port needs to match TINKERBELL_HTTP_AUTHORITY
      interval: 5s
      timeout: 2s
      retries: 3
    restart: unless-stopped

  tls-gen:
    image: cfssl/cfssl
    entrypoint: /bin/bash
    command:
      - /code/tls/generate.sh
    environment:
      FACILITY: ${FACILITY:-onprem}
    volumes:
      - ${PWD}/deploy:/code
      - certs:/certs/${FACILITY:-onprem}:rw

  tink-server-migration:
    image: quay.io/tinkerbell/tink:latest
    environment:
      ONLY_MIGRATION: "true"
      FACILITY: ${FACILITY:-onprem}
      PGDATABASE: tinkerbell
      PGHOST: db
      PGPASSWORD: tinkerbell
      PGPORT: 5432
      PGSSLMODE: disable
      PGUSER: tinkerbell
      TINKERBELL_GRPC_AUTHORITY: :42113
      TINKERBELL_HTTP_AUTHORITY: :42114
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: tinkerbell
      POSTGRES_PASSWORD: tinkerbell
      POSTGRES_USER: tinkerbell
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tinkerbell"]
      interval: 1s
      timeout: 1s
      retries: 30
    restart: unless-stopped

  tink-cli:
    build:
      context: ./cmd/tink-cli/
      dockerfile: Dockerfile
    environment:
      TINKERBELL_CERT_URL: http://tinkerbell:42114/cert
      TINKERBELL_GRPC_AUTHORITY: tinkerbell:42113
    depends_on:
      tinkerbell:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
  certs:
