version: '2.1'
services:
  certs:
    build: tls
    volumes:
      - ./certs:/certs

  rover:
    build: .
    environment: 
      FACILITY: ${FACILITY:-lab1}
      PACKET_ENV: ${PACKET_ENV:-testing}
      PACKET_VERSION: ${PACKET_VERSION:-5efab5ef3a42cb88f2d54f4ed3201c2dd6797b7d}
      ROLLBAR_TOKEN: ${ROLLBAR_TOKEN:-9b78d0ad01d1467aa92c49c3a349b79d}
      ROLLBAR_DISABLE: ${ROLLBAR_DISABLE:-0}
      PGDATABASE: rover
      PGHOST: db
      PGPASSWORD: rover
      PGPORT: 5432
      PGSSLMODE: disable
      PGUSER: rover
    depends_on:
      certs:
        condition: service_started
      fluentbit:
        condition: service_started
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- 127.0.0.1:42114/cert"]
      interval: 5s
      timeout: 2s
      retries: 30
    volumes: 
      - ./certs:/certs/${FACILITY}
        #logging:
        #driver: fluentd
        #options:
        #tag: rover
    ports:
      - 42113:42113/tcp
      - 42114:42114/tcp

  db:
    build:
      context: deploy
    environment:
      POSTGRES_DB: rover
      POSTGRES_PASSWORD: rover
      POSTGRES_USER: rover
    ports:
      - 5432:5432
    depends_on:
      - "fluentbit"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rover"]
      #test: ["CMD-SHELL","psql -U rover -c \"select COUNT(*) from hardware;\""]
      interval: 1s
      timeout: 1s
      retries: 30
    logging:
      driver: fluentd
      options:
        tag: db

  cli:
    build:
      context: .
      dockerfile: cmd/rover/Dockerfile
    environment:
      ROVER_GRPC_AUTHORITY: 127.0.0.1:42113
      ROVER_CERT_URL: http://127.0.0.1:42114/cert
    depends_on:
      - "fluentbit"
    logging:
      driver: fluentd
      options:
        tag: rover-cli
    network_mode: host

  cserver:
    build: ../cacher
    environment:
      FACILITY: ${FACILITY:-lab1}
      PACKET_API_AUTH_TOKEN: ${PACKET_API_AUTH_TOKEN}
      PACKET_API_URL: ${PACKET_API_URL:-https://lab-api.packet.net}
      PACKET_CONSUMER_TOKEN: ${PACKET_CONSUMER_TOKEN-djR2TAvbnkY92i8Ea2KFMZW6MusW1fk7qzeCUHgtnQRSsXnqxoCr6V2vhSxpqASf}
      PACKET_ENV: testing
      PACKET_VERSION: 5efab5ef3a42cb88f2d54f4ed3201c2dd6797b7d
      PGDATABASE: rover
      PGHOST: db
      PGPASSWORD: rover
      PGPORT: 5432
      PGSSLMODE: disable
      PGUSER: rover
      ROLLBAR_TOKEN: 9b78d0ad01d1467aa92c49c3a349b79d
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: prov=true
    depends_on:
      db:
        condition: service_healthy

  registry:
    build:
      context: registry
      args: 
        REGISTRY_USERNAME: username
        REGISTRY_PASSWORD: password
    environment: 
      REGISTRY_HTTP_ADDR: localhost:443
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/server.pem
      REGISTRY_HTTP_TLS_KEY: /certs/server-key.pem
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    volumes: 
      - ./certs:/certs
    depends_on:
      - fluentbit
    logging:
      driver: fluentd
      options:
        tag: registry
    network_mode: host

  elasticsearch:
    image: elasticsearch:7.3.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node

  kibana:
    image: kibana:7.3.0
    depends_on:
      - elasticsearch
    restart: always
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - 5601:5601

  fluentbit:
    image: fluent/fluent-bit:1.3
    ports:
      - 24224:24224
      - 24224:24224/udp
    depends_on:
      - kibana
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf

