{{- if .Values.rufio.deploy }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.rufio.rufioLeaderElectionRoleBindingName }}
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.rufio.rufioLeaderElectionRoleName }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.rufio.serviceAccountName }}
  namespace: {{ .Release.Namespace | quote }}
{{- end }}
