{{- if .Values.rufio.deploy }}
# permissions for end users to view machines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: machine-viewer-role
rules:
  - apiGroups:
      - bmc.tinkerbell.org
    resources:
      - machines
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - bmc.tinkerbell.org
    resources:
      - machines/status
    verbs:
      - get
{{- end }}
