{{- if .Values.rufio.deploy }}
# permissions for end users to edit machines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: machine-editor-role
rules:
  - apiGroups:
      - bmc.tinkerbell.org
    resources:
      - machines
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - bmc.tinkerbell.org
    resources:
      - machines/status
    verbs:
      - get
{{- end }}
