{{- if .Values.deploy }}
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ printf "%sBinding" .Values.rbac.type }}
metadata:
  name: {{ .Values.rbac.bindingName }}
  {{- if eq .Values.rbac.type "Role"  }}
  namespace: {{ .Release.Namespace | quote }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ .Values.rbac.type }}
  name: {{ .Values.rbac.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccountName }}
  namespace: {{ .Release.Namespace | quote }}
{{- end }}
