# name: dhcp
- op: add
  path: /spec/template/spec/containers/0/ports/0/hostPort
  value: 67
# name: tftp
- op: add
  path: /spec/template/spec/containers/0/ports/1/hostPort
  value: 69
# name: syslog
- op: add
  path: /spec/template/spec/containers/0/ports/2/hostPort
  value: 514
# name: http
- op: add
  path: /spec/template/spec/containers/0/ports/3/hostPort
  value: 80
