apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tink-system

resources:
  - ./../../base

patches:
  - path: deployment_patch.yaml
    target:
      kind: Deployment
      labelSelector: "app=tinkerbell-boots"
