# permissions for end users to edit baseboardmanagements.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: baseboardmanagement-editor-role
rules:
- apiGroups:
  - bmc.tinkerbell.org
  resources:
  - baseboardmanagements
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bmc.tinkerbell.org
  resources:
  - baseboardmanagements/status
  verbs:
  - get
