# permissions for end users to view baseboardmanagements.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: baseboardmanagement-viewer-role
rules:
- apiGroups:
  - bmc.tinkerbell.org
  resources:
  - baseboardmanagements
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bmc.tinkerbell.org
  resources:
  - baseboardmanagements/status
  verbs:
  - get
