# permissions for end users to edit bmcjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bmcjob-editor-role
rules:
- apiGroups:
  - bmc.tinkerbell.org
  resources:
  - bmcjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bmc.tinkerbell.org
  resources:
  - bmcjobs/status
  verbs:
  - get
