# permissions for end users to view bmcjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bmcjob-viewer-role
rules:
- apiGroups:
  - bmc.tinkerbell.org
  resources:
  - bmcjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bmc.tinkerbell.org
  resources:
  - bmcjobs/status
  verbs:
  - get
