# permissions for end users to edit bmctasks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bmctask-editor-role
rules:
- apiGroups:
  - bmc.tinkerbell.org
  resources:
  - bmctasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bmc.tinkerbell.org
  resources:
  - bmctasks/status
  verbs:
  - get
