# permissions for end users to view bmctasks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bmctask-viewer-role
rules:
- apiGroups:
  - bmc.tinkerbell.org
  resources:
  - bmctasks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bmc.tinkerbell.org
  resources:
  - bmctasks/status
  verbs:
  - get
