# permissions for end users to edit powercyclejobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: powercyclejob-editor-role
rules:
- apiGroups:
  - bmc.tinkerbell.org
  resources:
  - powercyclejobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bmc.tinkerbell.org
  resources:
  - powercyclejobs/status
  verbs:
  - get
