# permissions to do view Secrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secrets-viewer-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch