apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secrets-viewer-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secrets-viewer-role
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: system
