name: For each commit and PR
on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "v*"
  pull_request:

env:
  REGISTRY: quay.io
  IMAGE: quay.io/${{ github.repository }}
  CGO_ENABLED: 0
  GO_VERSION: "1.23"

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 5

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "${{ env.GO_VERSION }}"
          cache: true

      - name: Fix no space errors and Fetch Deps
        run: |
          # fixes "write /run/user/1001/355792648: no space left on device" error
          sudo mount -o remount,size=3G /run/user/1001 || true
          go get -t ./... && go mod tidy