apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tinkerbell
images:
  - name: quay.io/tinkerbell/boots
    newTag: latest
resources:
  - github.com/tinkerbell/tink/config/crd?ref=main
  - namespace.yaml
  - rbac.yaml
  - deployment.yaml

patches:
  - path: deployment_patch.yaml
    target:
      kind: Deployment
      labelSelector: "app=tinkerbell-boots"
