apiVersion: v1
kind: ServiceAccount
metadata:
  name: tinkerbell-smee
  namespace: tink-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tinkerbell-smee-role
  namespace: tink-system
rules:
  - apiGroups:
      - tinkerbell.org
    resources:
      - hardware
      - hardware/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - tinkerbell.org
    resources:
      - workflows
      - workflows/status
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tinkerbell-smee-role
  namespace: tink-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tinkerbell-smee-role
subjects:
  - kind: ServiceAccount
    name: tinkerbell-smee
    namespace: tink-system
---

