{{- if .Values.stack.hook.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: download-hook
  namespace: {{ .Release.Namespace }}
data:
  entrypoint.sh: |-
    #!/usr/bin/env bash
    # This script is designed to download the Hook artifacts.
    set -euxo pipefail
    cd /output
    rm -f *.tar.gz checksum.txt vmlinuz* initramfs*
    base_loc="{{ .Values.stack.hook.downloadURL }}"
    files="$base_loc/hook_aarch64.tar.gz $base_loc/hook_x86_64.tar.gz $base_loc/checksum.txt"
    tmp_dir=$(mktemp -d)
    for f in ${files}; do
      echo "${f}"
      wget -P "${tmp_dir}" "${f}"
    done
    # releases of HookOS > 0.8.1 provide more binaries.
    # We only need the hook_aarch64 and hook_x86_64 binaries so we filter out the rest.
    (cd "${tmp_dir}" && sed -i '/hook_x86_64\|hook_aarch64/!d' checksum.txt && sha512sum -c checksum.txt)
    mv "${tmp_dir}"/checksum.txt .
    for f in ${tmp_dir}/*.tar.gz; do tar --no-same-permissions --overwrite -ozxvf "${f}" && rm -f "${f}"; done
    rm -rf "${tmp_dir}"
    sleep infinity & PID=$!
    trap "kill $PID" INT TERM
    wait $PID
{{- end }}
