# The NGINX ConfigMap is in a separate file because its checksum is used to trigger updates in
# the deployment.
{{ if .Values.stack.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: {{ .Release.Namespace | quote }}
data:
  nginx.conf: |
    worker_processes 1;
    events {
        worker_connections  1024;
    }
    user root;

    http {
      server {
        listen {{ .Values.hegel.service.port }};
        location / {
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          resolver $POD_NAMESERVER;
          set $hegel_dns {{ .Values.hegel.name }}.{{ .Release.Namespace }}.svc.cluster.local.; # needed in Kubernetes for dynamic DNS resolution

          proxy_pass http://$hegel_dns:{{ .Values.hegel.service.port }};
        }
      }

      server {
        listen {{ .Values.tink.server.service.port }};
        http2 on;
        location / {
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          resolver $POD_NAMESERVER;
          set $tink_dns {{ .Values.tink.server.name }}.{{ .Release.Namespace }}.svc.cluster.local.; # needed in Kubernetes for dynamic DNS resolution

          grpc_pass grpc://$tink_dns:{{ .Values.tink.server.service.port }};
        }
      }

       server {
        listen {{ .Values.stack.hook.port }};
        location / {
          root /usr/share/nginx/html;
        }
      }
    }
{{- end }}