version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "America/New_York"
    reviewers:
      - chrisdoherty4
      - jacobweinstock

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "America/New_York"
    reviewers:
      - chrisdoherty4
      - jacobweinstock

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "America/New_York"
    reviewers:
      - chrisdoherty4
      - jacobweinstock
