stack:
  enabled: true
  name: tink-stack
  service:
    enabled: true
    type: LoadBalancer
  selector:
    app: tink-stack
  loadBalancerIP: &publicIP 192.168.2.112
  lbClass: kube-vip.io/kube-vip-class
  # Once the Kubernetes Gateway API is more stable, we will use that for all services instead of nginx.
  image: nginx:1.25.1
  hook:
    enabled: true
    name: hook-files
    port: 8080
    image: alpine
    downloadsDest: /opt/hook
    downloads:
      - url: https://github.com/tinkerbell/hook/releases/download/v0.8.0/hook_x86_64.tar.gz
        sha512sum: 498cccba921c019d4526a2a562bd2d9c8efba709ab760fa9d38bd8de1efeefc8e499c9249af9571aa28a1e371e6c928d5175fa70d5d7addcf3dd388caeff1a45
      - url: https://github.com/tinkerbell/hook/releases/download/v0.8.0/hook_aarch64.tar.gz
        sha512sum: 56e3959722c9ae85aec6c214448108e2dc1d581d2c884ca7a23265c1ae28489589481730fbb941fac8239f6222f9b5bb757987a5238f20194e184ae7e83b6a5b
  kubevip:
    enabled: true
    name: kube-vip
    image: ghcr.io/kube-vip/kube-vip:v0.5.12
    imagePullPolicy: IfNotPresent
    roleName: kube-vip-role
    roleBindingName: kube-vip-rolebinding
    # Customize the interface KubeVIP advertises on. When unset, KubeVIP will autodetect the
    # interface.
    #interface: enp0s8
  relay: # relay allows us to listen and respond to layer broadcast DHCP requests
    name: dhcp-relay
    enabled: true
    # This image (ghcr.io/jacobweinstock/dhcrelay) is used because the other public dhcprelay images out there (`modem7/dhcprelay`)
    # doesn't respect signals properly when run as PID 1.
    image: ghcr.io/jacobweinstock/dhcrelay
    maxHopCount: 10
    # sourceInterface is the Host/Node interface to use for listening for DHCP broadcast packets.
    # When unset, the interface from the default route will be used.
    # sourceInterface: eno1

# -- Overrides
# The values defined here override those in the individual charts. Some of them require tweaking
# before deployment as they are environment dependent; others are surfaced for convenience.
#
# See individual chart documentation for additional detail.

boots:
  image: quay.io/tinkerbell/boots:v0.9.0
  tinkWorkerImage: quay.io/tinkerbell/tink-worker:v0.9.0
  trustedProxies: []
  # This will be the IP address that machines use to reach Boots (via unicast for DHCP) for netbooting.
  # This should be the same as `stack.loadBalancerIP`.
  remoteIp: *publicIP
  tinkServer:
    # This should be the same as `stack.loadBalancerIP`.
    ip: *publicIP
  osieBase:
    # This should be the same as `stack.loadBalancerIP`.
    ip: *publicIP

hegel:
  image: quay.io/tinkerbell/hegel:v0.11.0
  trustedProxies: []

rufio:
  image: quay.io/tinkerbell/rufio:v0.3.1

tink:
  controller:
    image: quay.io/tinkerbell/tink-controller:v0.9.0
  server:
    image: quay.io/tinkerbell/tink:v0.9.0
