namespace: tink-system
createNamespace: true

# service for the stack
service:
  enabled: true
  name: tink-stack
  selector:
    app: tink-stack
    lbtype: external
  ip: 192.168.2.111
  lbClass: kube-vip.io/kube-vip-class
  image: nginx:1.23.1

kubevip:
  enabled: true
  name: kube-vip
  image: ghcr.io/kube-vip/kube-vip:v0.5.0
  imagePullPolicy: IfNotPresent
  roleName: kube-vip-role
  roleBindingName: kube-vip-rolebinding
  interface: enp0s9

tink:
  namespace: tink-system

boots:
  namespace: tink-system
  boots:
    env:
    - name: DATA_MODEL_VERSION
      value: "kubernetes"
    - name: FACILITY_CODE
      value: "lab1"
    - name: HTTP_BIND
      value: ":80"
    - name: MIRROR_BASE_URL
      value: http://192.168.2.150:8080
    - name: PUBLIC_IP
      value: 192.168.2.111
    - name: PUBLIC_SYSLOG_FQDN
      value: 192.168.2.111
    - name: SYSLOG_BIND
      value: :514
    - name: TINKERBELL_GRPC_AUTHORITY
      value: 192.168.2.111:42113
    - name: TINKERBELL_TLS
      value: "false"
    - name: BOOTS_LOG_LEVEL
      value: "debug"
    - name: BOOTS_EXTRA_KERNEL_ARGS
      value: "tink_worker_image=quay.io/tinkerbell/tink-worker:latest"
    - name: TRUSTED_PROXIES
      value: 10.42.0.68/24
    hostNetwork: true


hegel:
  namespace: tink-system
  hegel:
    env:
    - name: TRUSTED_PROXIES
      value: 10.42.0.0/24

rufio:
  namespace: tink-system

