---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - bmc.tinkerbell.org
  resources:
  - job
  - job/status
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - tinkerbell.org
  resources:
  - hardware
  - hardware/status
  - templates
  - templates/status
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tinkerbell.org
  resources:
  - workflows
  - workflows/status
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
