{{- if .Values.boots.deploy }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.boots.name }}
  name:  {{ .Values.boots.name }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: {{ .Values.boots.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.boots.name }}
      stack: tinkerbell
      {{- with .Values.boots.selector }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  template:
    metadata:
      labels:
        app: {{ .Values.boots.name }}
        stack: tinkerbell
        {{- with .Values.boots.selector }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - image: {{ .Values.boots.image }}
          imagePullPolicy: {{ .Values.boots.imagePullPolicy }}
          {{- if .Values.boots.args }}
          args: 
          {{- range .Values.boots.args }}
            - {{ . }}
          {{- end }}
          {{- end }}
          env:
            - name: TRUSTED_PROXIES
              value: {{ .Values.boots.trustedProxies }}
          {{- if .Values.boots.env }}
            {{- range $i, $env := .Values.boots.env }}
            - name: {{ $env.name | quote }}
              value: {{ $env.value | quote }}
            {{- end }}
          {{- end }}
          {{- if not .Values.boots.hostNetwork }}
          ports:
            {{- range .Values.boots.ports }}
            - containerPort: {{ .targetPort }}
              name: {{ .name }}
              protocol: {{ .protocol }}
            {{- end }}
          {{- end }}
          name: {{ .Values.boots.name }}
          resources:
            limits:
              cpu: {{ .Values.boots.resources.limits.cpu }}
              memory: {{ .Values.boots.resources.limits.memory }}
            requests:
              cpu: {{ .Values.boots.resources.requests.cpu }}
              memory: {{ .Values.boots.resources.requests.memory }}
      serviceAccountName: {{ .Values.boots.name }}
      {{- if .Values.boots.hostNetwork }}
      hostNetwork: true
      {{- end }}
{{- end }}
