{{- if and .Values.deploy .Values.service.enabled -}}
{{- $loadBalancerIP := default .Values.remoteIp .Values.service.loadBalancerIP }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  {{- if .Values.service.class }}
  loadBalancerClass: {{ .Values.service.class }}
  {{- end }}
  loadBalancerIP: {{ $loadBalancerIP }}
  externalTrafficPolicy: Local
  {{- end }}
  ports:
  {{- include "boots.ports" ( merge ( dict "PortKey" "port" ) .Values  ) | indent 2 }}
  selector:
    app: {{ .Values.name }}
{{- end -}}
