name: For each commit and PR
on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "v*"
  pull_request:

jobs:
  validation:
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 0
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17"
      - name: goimports
        run: go get golang.org/x/tools/cmd/goimports && goimports -d . | (! grep .)
      - name: go vet
        run: go vet ./...
      - name: lint
        run: make lint
      - name: go test coverage
        run: go test -coverprofile=coverage.txt ./...
      - name: upload codecov
        run: bash <(curl -s https://codecov.io/bash)
  docker-images:
    runs-on: ubuntu-latest
    needs: [validation]
    steps:
      - name: Docker Image Tag for Sha
        id: docker-image-tag
        run: |
          echo ::set-output name=tags::quay.io/tinkerbell/hegel:latest,quay.io/tinkerbell/hegel:sha-${GITHUB_SHA::8}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to quay.io
        uses: docker/login-action@v1
        if: ${{ startsWith(github.ref, 'refs/heads/main') }}
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: quay.io/tinkerbell/hegel
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./cmd/hegel/Dockerfile
          cache-from: type=registry,ref=quay.io/tinkerbell/hegel:latest
          push: ${{ startsWith(github.ref, 'refs/heads/main') }}
          tags: ${{ steps.docker-image-tag.outputs.tags }}
          platforms: linux/amd64,linux/arm64
